name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version to release"
        required: true
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - realm-extend
    tags:
      - "v*"
  pull_request:
    branches:
      - realm-extend
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
  
env:
  REGISTRY: docker.io
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs:
          - { goos: windows, goarch: amd64, goamd64: v3, output: amd64-v3 }

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      if: ${{ matrix.jobs.goversion == '' }}
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
        go-version: '1.26'

    - name: Set up Go
      if: ${{ matrix.jobs.goversion != '' && matrix.jobs.goversion != 'custom' }}
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
        go-version: ${{ matrix.jobs.goversion }}

    - name: Set up Go1.26 loongarch abi1
      if: ${{ matrix.jobs.goarch == 'loong64' && matrix.jobs.abi == '1' }}
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-download-base-url: 'https://github.com/MetaCubeX/loongarch64-golang/releases/download/1.26.0'
        go-version: 1.26.0

    - name: Verify Go installation
      run: go version

    - name: Verify Go env
      run: go env

    - name: Set variables
      run: |
        VERSION="${GITHUB_REF_NAME,,}"
        VERSION="${VERSION//\//-}"
        PackageVersion="${VERSION}"
        if [ -n "${{ github.event.inputs.version }}" ]; then
          VERSION=${{ github.event.inputs.version }}
          PackageVersion="${VERSION#v}"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "PackageVersion=${PackageVersion}" >> $GITHUB_ENV
      
        echo "BUILDTIME=$(date)" >> $GITHUB_ENV
        echo "CGO_ENABLED=0" >> $GITHUB_ENV
        echo "BUILDTAG=-extldflags --static" >> $GITHUB_ENV
        echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

    - name: Setup NDK
      if: ${{ matrix.jobs.goos == 'android' }}
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r29-beta1

    - name: Set NDK path
      if: ${{ matrix.jobs.goos == 'android' }}
      run: |
        echo "CC=${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{matrix.jobs.ndk}}-clang" >> $GITHUB_ENV
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "BUILDTAG=" >> $GITHUB_ENV

    - name: Test
      if: ${{ matrix.jobs.test == 'test' }}
      run: |
        export SKIP_CONCURRENT_TEST=1
        export SKIP_INTEROP_TEST=1
        go test ./...
        echo "---test with_gvisor---"
        go test ./... -tags "with_gvisor" -count=1

    - name: Update CA
      run: |
        sudo apt-get update && sudo apt-get install ca-certificates
        sudo update-ca-certificates
        cp -f /etc/ssl/certs/ca-certificates.crt component/ca/ca-certificates.crt

    - name: Build core
      env:
        GOOS: ${{matrix.jobs.goos}}
        GOARCH: ${{matrix.jobs.goarch}}
        GOAMD64: ${{matrix.jobs.goamd64}}
        GO386: ${{matrix.jobs.go386}}
        GOARM: ${{matrix.jobs.goarm}}
        GOMIPS: ${{matrix.jobs.gomips}}
      run: |
        go env
        go build -v -tags "with_gvisor" -trimpath -ldflags "${BUILDTAG} -X 'github.com/metacubex/mihomo/constant.Version=${VERSION}' -X 'github.com/metacubex/mihomo/constant.BuildTime=${BUILDTIME}' -w -s -buildid="
        if [ "${{matrix.jobs.goos}}" = "windows" ]; then
          cp mihomo.exe mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
          zip -r mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.zip mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
        else
          cp mihomo mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
          gzip -c mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}} > mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.gz
          rm mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
        fi

    - name: Package DEB
      if: matrix.jobs.debian != ''
      run: |
        set -xeuo pipefail
        sudo gem install fpm
        cp .github/release/.fpm_systemd .fpm

        fpm -t deb \
          -v "${PackageVersion}" \
          -p "mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.deb" \
          --architecture ${{ matrix.jobs.debian }} \
          mihomo=/usr/bin/mihomo

    - name: Package RPM
      if: matrix.jobs.rpm != ''
      run: |
        set -xeuo pipefail
        sudo gem install fpm
        cp .github/release/.fpm_systemd .fpm

        fpm -t rpm \
          -v "${PackageVersion}" \
          -p "mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.rpm" \
          --architecture ${{ matrix.jobs.rpm }} \
          mihomo=/usr/bin/mihomo

    - name: Package Pacman
      if: matrix.jobs.pacman != ''
      run: |
        set -xeuo pipefail
        sudo gem install fpm
        sudo apt-get update && sudo apt-get install -y libarchive-tools
        cp .github/release/.fpm_systemd .fpm

        fpm -t pacman \
          -v "${PackageVersion}" \
          -p "mihomo-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.pkg.tar.zst" \
          --architecture ${{ matrix.jobs.pacman }} \
          mihomo=/usr/bin/mihomo

    - name: Pack Golang Toolchain
      if: ${{ matrix.jobs.goversion == '' && matrix.jobs.tarball == 'tarball' }}
      run: |
        mkdir -p $GITHUB_WORKSPACE/toolchain/go
        cp -r $(go env GOROOT)/* $GITHUB_WORKSPACE/toolchain/go/
        cd $GITHUB_WORKSPACE/toolchain/
        tar -czf $GITHUB_WORKSPACE/toolchain.tar.gz .
        rm -rf $GITHUB_WORKSPACE/toolchain

    - name: Pack GoMod Vendor
      if: ${{ matrix.jobs.goversion == '' && matrix.jobs.tarball == 'tarball' }}
      run: |
        go mod vendor
        tar -czf $GITHUB_WORKSPACE/vendor.tar.gz vendor

    - name: Save version
      run: |
        echo ${VERSION} > version.txt
      shell: bash

    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
        name: "${{ matrix.jobs.goos }}-${{ matrix.jobs.output }}"
        path: |
          mihomo*.gz
          mihomo*.deb
          mihomo*.rpm
          mihomo*.pkg.tar.zst
          mihomo*.zip
          toolchain.tar.gz
          vendor.tar.gz
          version.txt
          checksums.txt
